name: Translation Automation

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'src/main/resources/messages_en.properties'
      - 'src/main/resources/glossaries/glossaries_*.csv'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      properties_changed: ${{ steps.check-files.outputs.properties_changed }}
      glossaries_changed: ${{ steps.check-files.outputs.glossaries_changed }}
      changed_glossaries: ${{ steps.check-files.outputs.changed_glossaries }}
      diff_count: ${{ steps.check-diff.outputs.diff_count }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changed files
        id: check-files
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "src/main/resources/messages_en.properties"; then
            echo "properties_changed=true" >> $GITHUB_OUTPUT
          else
            echo "properties_changed=false" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "src/main/resources/glossaries/glossaries_.*\.csv"; then
            echo "glossaries_changed=true" >> $GITHUB_OUTPUT
            CHANGED_GLOSSARIES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep "glossaries_.*\.csv" | sed -E 's/.*glossaries_([a-z]{2})\.csv/\1/' | tr '\n' ',' | sed 's/,$//')
            echo "changed_glossaries=$CHANGED_GLOSSARIES" >> $GITHUB_OUTPUT
          else
            echo "glossaries_changed=false" >> $GITHUB_OUTPUT
            echo "changed_glossaries=''" >> $GITHUB_OUTPUT
          fi
      - name: Check diff content
        id: check-diff
        run: |
          DIFF_COUNT=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- src/main/resources/messages_en.properties | grep '^[+-]' | grep -v '^[+-]\{3\}' | wc -l)
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT

  trigger-translation:
    needs: check-changes
    if: needs.check-changes.outputs.properties_changed == 'true' || needs.check-changes.outputs.glossaries_changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      workflow_id: ${{ steps.trigger.outputs.workflow_id }}
    steps:
      - name: Trigger Translation Workflow
        id: trigger
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: 'Ashutoshk-DigiCert',
              repo: 'DTMmock',
              workflow_id: 'translate.yml',
              ref: 'main',
              inputs: {
                properties_changed: '${{ needs.check-changes.outputs.properties_changed }}',
                glossaries_changed: '${{ needs.check-changes.outputs.glossaries_changed }}',
                changed_glossaries: '${{ needs.check-changes.outputs.changed_glossaries }}',
                diff_count: '${{ needs.check-changes.outputs.diff_count }}'
              }
            });
            return response.data.id;

  download-translations:
    needs: trigger-translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Wait for translation workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const MAX_ATTEMPTS = 30;
            const SLEEP_TIME = 30000;
            
            for (let i = 0; i < MAX_ATTEMPTS; i++) {
              console.log(`Attempt ${i + 1} of ${MAX_ATTEMPTS}`);
              const runs = await github.rest.actions.listWorkflowRuns({
                owner: 'Ashutoshk-DigiCert',
                repo: 'DTMmock',
                workflow_id: 'translate.yml',
                status: 'completed',
                per_page: 1
              });
            
              if (runs.data.workflow_runs.length > 0) {
                const run = runs.data.workflow_runs[0];
                if (run.conclusion === 'success') {
                  console.log('Translation workflow completed successfully');
                  break;
                } else if (run.conclusion === 'failure') {
                  throw new Error('Translation workflow failed');
                }
              }
            
              await new Promise(resolve => setTimeout(resolve, SLEEP_TIME));
            }

      - name: Download Artifacts
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: 'Ashutoshk-DigiCert',
              repo: 'DTMmock'
            });
            
            const artifact = artifacts.data.artifacts.find(a => a.name === 'translated-files');
            if (!artifact) {
              throw new Error('No translation artifacts found');
            }
            
            const download = await github.rest.actions.downloadArtifact({
              owner: 'Ashutoshk-DigiCert',
              repo: 'DTMmock',
              artifact_id: artifact.id,
              archive_format: 'zip'
            });

      - name: Update Repository Files
        run: |
          unzip translated-files.zip -d translated-files
          cp -r translated-files/* src/main/resources/

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/main/resources/messages_*.properties
          git add src/main/resources/glossaries/*.csv
          git commit -m "Updated translations and glossaries"
          git push origin ${{ github.event.pull_request.head.ref }}