name: Translation Automation

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'src/main/resources/messages_en.properties'
      - 'src/main/resources/glossaries/glossaries_*.csv'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      properties_changed: ${{ steps.check-files.outputs.properties_changed }}
      glossaries_changed: ${{ steps.check-files.outputs.glossaries_changed }}
      changed_glossaries: ${{ steps.check-files.outputs.changed_glossaries }}
      diff_count: ${{ steps.check-diff.outputs.diff_count }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check changed files
        id: check-files
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "src/main/resources/messages_en.properties"; then
            echo "properties_changed=true" >> $GITHUB_OUTPUT
          else
            echo "properties_changed=false" >> $GITHUB_OUTPUT
          fi
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "src/main/resources/glossaries/glossaries_.*\.csv"; then
            echo "glossaries_changed=true" >> $GITHUB_OUTPUT
            CHANGED_GLOSSARIES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep "glossaries_.*\.csv" | sed -E 's/.*glossaries_([a-z]{2})\.csv/\1/' | tr '\n' ',' | sed 's/,$//')
            echo "changed_glossaries=$CHANGED_GLOSSARIES" >> $GITHUB_OUTPUT
          else
            echo "glossaries_changed=false" >> $GITHUB_OUTPUT
            echo "changed_glossaries=''" >> $GITHUB_OUTPUT
          fi
      - name: Check diff content
        id: check-diff
        run: |
          DIFF_COUNT=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- src/main/resources/messages_en.properties | grep '^[+-]' | grep -v '^[+-]\{3\}' | wc -l)
          echo "diff_count=$DIFF_COUNT" >> $GITHUB_OUTPUT

  trigger-translation:
    needs: check-changes
    if: needs.check-changes.outputs.properties_changed == 'true' || needs.check-changes.outputs.glossaries_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Debug outputs
        run: |
          echo "properties_changed: ${{ needs.check-changes.outputs.properties_changed }}"
          echo "glossaries_changed: ${{ needs.check-changes.outputs.glossaries_changed }}"
          echo "changed_glossaries: ${{ needs.check-changes.outputs.changed_glossaries }}"
          echo "diff_count: ${{ needs.check-changes.outputs.diff_count }}"
      - name: Trigger Translation Project Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Ashutoshk-DigiCert',
              repo: 'DTMmock',
              workflow_id: 'translate.yml',
              ref: 'main',
              inputs: {
                properties_changed: '${{ needs.check-changes.outputs.properties_changed }}',
                glossaries_changed: '${{ needs.check-changes.outputs.glossaries_changed }}',
                changed_glossaries: '${{ needs.check-changes.outputs.changed_glossaries }}',
                diff_count: '${{ needs.check-changes.outputs.diff_count }}'
              }
            });

      - name: Wait for Translation Workflow to Complete
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            const response = await github.rest.actions.listWorkflowRunsForRepo({
              owner: 'Ashutoshk-DigiCert',
              repo: 'DTMmock',
              workflow_id: 'translate.yml',
              status: 'in_progress'
            });
            if (response.data.total_count > 0) {
              throw new Error('Translation workflow is still running.');
            }

      - name: Download Translated Files
        uses: actions/download-artifact@v3
        with:
          name: translated-files
          path: translated-files/
      - name: Copy Translated Files Back
        run: |
          cp -r translated-files/* src/main/resources/
      - name: Commit Translated Files
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add src/main/resources/messages_*.properties
          git add src/main/resources/glossaries/*.csv
          git commit -m "Updated translations and glossaries"
      - name: Push Translated Files
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
      - name: Create Pull Request for Translations
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ":globe_with_meridians: Update translations"
          title: ":globe_with_meridians: Update translations for PR #${{ github.event.pull_request.number }}"
          body: |
            ## Automated Translation Updates

            Changes detected in:
            ${{ needs.check-changes.outputs.properties_changed == 'true' && '- messages_en.properties' || '' }}
            ${{ needs.check-changes.outputs.glossaries_changed == 'true' && '- glossaries files' || '' }}

            Number of changes: ${{ needs.check-changes.outputs.diff_count }}
            Original PR: #${{ github.event.pull_request.number }}
          branch: translations/pr-${{ github.event.pull_request.number }}
          base: ${{ github.event.pull_request.base.ref }}
          labels: automated-translation
          delete-branch: true